import { Metadata } from 'next'

import 'bootstrap/dist/css/bootstrap.css'
import '@/styles/index.sass'

export const metadata: Metadata = {
  // General
  applicationName: 'Linkchar Next Template',
  generator: 'Next.js',
  title: {
    default: 'Linkchar',
    template: '%s | Linkchar',
  },
  description: 'Linkchar Next Template - Created by Lucas Ojeda De Sousa (Lukway)',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
  referrer: 'origin-when-cross-origin',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
  category: 'Software Development',
  // Author
  authors: [{ name: 'Lucas Ojeda De Sousa (Lukway)', url: 'luwkay.dev@gmail.com' }],
  creator: 'Lucas Ojeda De Sousa (Lukway)',
  publisher: 'Linkchar Next Template',
  // URL
  metadataBase: new URL('http://localhost:3000'),
  alternates: {
    canonical: '/',
  },
  // SEO
  keywords: ['Linkchar'],
  openGraph: {
    title: 'Linkchar',
    description: 'Generated by create next app',
    url: 'http://localhost:3000',
    type: 'book',
    siteName: 'Linkchar Software Development',
    images: [
      {
        url: 'https://nextjs.org/og.png',
        width: 800,
        height: 600,
      },
      {
        url: 'https://nextjs.org/og-alt.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en_US',
    authors: ['Lucas Ojeda De Sousa (Lukway)'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Next.js',
    description: 'Linkchar Next Template',
    siteId: '1467726470533754880',
    creator: '@nextjs',
    creatorId: '1467726470533754880',
    images: ['https://nextjs.org/og.png'],
  },
  // Robots
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Icons
  icons: {
    icon: [
      { url: '/favicon16.svg', sizes: '16x16' },
      { url: '/favicon32.svg', sizes: '32x32' },
      { url: '/favicon36.svg', sizes: '36x36' },
      { url: '/favicon48.svg', sizes: '48x48' },
      { url: '/favicon72.svg', sizes: '72x72' },
      { url: '/favicon96.svg', sizes: '96x96' },
      { url: '/favicon128.svg', sizes: '128x128' },
      { url: '/favicon144.svg', sizes: '144x144' },
      { url: '/favicon152.svg', sizes: '152x152' },
      { url: '/favicon192.svg', sizes: '192x192' },
      { url: '/favicon256.svg', sizes: '256x256' },
      { url: '/favicon512.svg', sizes: '512x512' },
    ],
    shortcut: {
      url: '/favicon144.png',
      sizes: '144x144',
    },
    apple: [
      { url: '/favicon57.svg', sizes: '57x57' },
      { url: '/favicon60.svg', sizes: '60x60' },
      { url: '/favicon72.svg', sizes: '72x72' },
      { url: '/favicon76.svg', sizes: '76x76' },
      { url: '/favicon114.svg', sizes: '114x114' },
      { url: '/favicon120.svg', sizes: '120x120' },
      { url: '/favicon144.svg', sizes: '144x144' },
      { url: '/favicon152.svg', sizes: '152x152' },
      { url: '/favicon180.svg', sizes: '180x180' },
    ],
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/favicon144.png',
      sizes: '144x144',
    },
  },
  // Verification
  verification: {
    google: 'google',
    yandex: 'yandex',
    yahoo: 'yahoo',
    other: {
      me: ['contact@linkchar.com', 'https://linkchar.com'],
    },
  },
  // Apple
  appleWebApp: {
    title: 'Linkchar',
    statusBarStyle: 'black-translucent',
    startupImage: [
      'image path',
      {
        url: 'image path',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  }
}

interface Props {
  children: React.ReactNode
}
export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <h1>Layout</h1>
        { children }
      </body>
    </html>
  )
}
