allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  cypress: true
  husky: true
  playwright-webkit: true
  sass: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - react-tooltip@6.0.7
