name: CI (Checks & Tests)

on:
  push:
    branches: [main, develop, feature/general-improvements]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    env:
      # --- Client side variables ---
      API_URL: ${{ vars.API_URL }}
      MEDIA_URL: ${{ vars.MEDIA_URL }}
      CLARITY_ID: ${{ vars.CLARITY_ID }}
      IS_PRODUCTION: ${{ vars.IS_PRODUCTION }}

      # --- Server side variables ---
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_DEFAULT_USER: ${{ secrets.AUTH_DEFAULT_USER }}
      AUTH_DEFAULT_PASSWORD: ${{ secrets.AUTH_DEFAULT_PASSWORD }}
      MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Config Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Instalar Binario de Cypress
        run: pnpm exec cypress install

      - name: Run ESLint & Typescript
        run: pnpm run check

      - name: Run Cypress (E2E)
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: pnpm run build
          start: pnpm run serve
          wait-on: "http://localhost:3000"
